---
- hosts: localhost
  tasks:
    - name: Create a Deployment for Hello Go.
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: hello-go
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: hello-go
            template:
              metadata:
                labels:
                  app: hello-go
              spec:
                containers:
                - name: hello-go
                  image: "hello-go:latest"
                  imagePullPolicy: IfNotPresent
                  ports:
                  - containerPort: 8180
