---
- hosts: localhost
  become: yes
  collections:
    - kubernetes.core
  tasks:
    - name: Retrieve helm binary archive.
      unarchive:
        src: https://get.helm.sh/helm-v3.4.1-linux-amd64.tar.gz
        dest: /tmp
        creates: /usr/local/bin/helm
        remote_src: yes

    - name: Move helm binary into place.
      command: cp /tmp/linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    - name: Add Bitnami's chart repository.
      community.kubernetes.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"


    - name: upgrade all packages
      yum:
        name: "*"
        state: latest
      become: True


    - name: Ensure pyhelm is installed.
      pip:
        name:
          - pyhelm
        extra_args: --ignore-installed requests
        state: present

    - name: Install older version of requests for pyhelm
      pip:
        name:
          - pyyaml
        state: present

    - name: Ensure pyhelm is installed.
      pip:
        name:
          - pyhelm
        state: present

    - name: Install Helm env plugin
      community.kubernetes.helm_plugin:
        plugin_path: https://github.com/adamreese/helm-env
        state: present
        release_namespace: default


    - name: Git clone stable repo on HEAD
      ansible.builtin.git:
        repo: "http://github.com/helm/charts.git"
        dest: /tmp/helm_repo

    - name: Install Nginx Chart
      kubernetes.core.helm:
        name: nginx-server
        namespace: testing
        chart_ref: bitnami/nginx


    - name: Deploy latest version of Drupal
      helm:
        name: test-drupal
        chart: stable/drupal
        namespace: default
      become: True

