---
- hosts: localhost
  become: no
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    image_name: nginx
    image_tag: 1.14.2
    replicas: 2
  tasks:
    - name: Create a Deployment for Nginx frontend
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: default
          spec:
            replicas: "{{ replicas }}"
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: "{{ image_name }}:{{ image_tag }}"
                  imagePullPolicy: IfNotPresent
                  ports:
                  - containerPort: 80
