---
- hosts: localhost
  become: no
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    image_name: heywoodlh/tsunami
    image_tag: latest
    replicas: 2
  tasks:
    - name: Retrieve helm binary archive.
      unarchive:
        src: https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
        dest: /tmp
        creates: /usr/local/bin/helm
        remote_src: yes

    - name: Move helm binary into place.
      command: cp /tmp/linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    - name: Create a Deployment for Hello Go.
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: tsunami-scanner
            namespace: default
          spec:
            replicas: "{{ replicas }}"
            selector:
              matchLabels:
                app: tsunami-scanner
            template:
              metadata:
                labels:
                  app: tsunami-scanner
              spec:
                containers:
                - name: tsunami
                  image: "{{ image_name }}:{{ image_tag }}"
                  imagePullPolicy: IfNotPresent
                  ports:
                  - containerPort: 8888
